<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'MyErrorHandler\Exception\BadRequestException'         => __DIR__ . '/src/MyErrorHandler/Exception/BadRequestException.php',
  'MyErrorHandler\Exception\Exception'                   => __DIR__ . '/src/MyErrorHandler/Exception/Exception.php',
  'MyErrorHandler\Exception\ExceptionInterface'          => __DIR__ . '/src/MyErrorHandler/Exception/ExceptionInterface.php',
  'MyErrorHandler\Exception\NotFoundException'           => __DIR__ . '/src/MyErrorHandler/Exception/NotFoundException.php',
  'MyErrorHandler\Exception\ServiceUnavailableException' => __DIR__ . '/src/MyErrorHandler/Exception/ServiceUnavailableException.php',
  'MyErrorHandler\Exception\UnauthorizedException'       => __DIR__ . '/src/MyErrorHandler/Exception/UnauthorizedException.php',
  'MyErrorHandler\Module'                                => __DIR__ . '/src/MyErrorHandler/Module.php',
  'MyErrorHandler\Strategy\ExceptionStrategy'            => __DIR__ . '/src/MyErrorHandler/Strategy/ExceptionStrategy.php',
  'MyErrorHandler\Strategy\NotFoundStrategy'             => __DIR__ . '/src/MyErrorHandler/Strategy/NotFoundStrategy.php',
  'MyErrorHandler\Strategy\StrategyInterface'            => __DIR__ . '/src/MyErrorHandler/Strategy/StrategyInterface.php',
);
